// BlobCats © the BlobCats contributors, Apache-2.0 (assets/blobcats/LICENSE).
// Keys are what `#blobcat("...")` accepts; values are relative to `lib.typ`,
// which is where `image()` is called, not to this file.
// One entry per PNG in the BlobCats submodule (assets/blobcats/PNGs/BlobCats/),
// key = lowercase filename with `BlobCat` and the separators dropped.
// Adding a cat means adding one line here (AGENTS.md).
#let blobcat-files = (
  "acab": "assets/blobcats/PNGs/BlobCats/BlobCat_ACAB.png",
  "alien": "assets/blobcats/PNGs/BlobCats/BlobCat_Alien.png",
  "amused": "assets/blobcats/PNGs/BlobCats/BlobCat_Amused.png",
  "angel": "assets/blobcats/PNGs/BlobCats/BlobCat_Angel.png",
  "angery": "assets/blobcats/PNGs/BlobCats/BlobCat_Angery.png",
  "angryhammer": "assets/blobcats/PNGs/BlobCats/BlobCat_AngryHammer.png",
  "arrow": "assets/blobcats/PNGs/BlobCats/BlobCat_Arrow.png",
  "astonished": "assets/blobcats/PNGs/BlobCats/BlobCat_Astonished.png",
  "aww": "assets/blobcats/PNGs/BlobCats/BlobCat_Aww.png",
  "ayo": "assets/blobcats/PNGs/BlobCats/BlobCat_Ayo.png",
  "bandage": "assets/blobcats/PNGs/BlobCats/BlobCat_Bandage.png",
  "bigsob": "assets/blobcats/PNGs/BlobCats/BlobCat_BigSob.png",
  "blankie": "assets/blobcats/PNGs/BlobCats/BlobCat_Blankie.png",
  "blankiescared": "assets/blobcats/PNGs/BlobCats/BlobCat_BlankieScared.png",
  "blep": "assets/blobcats/PNGs/BlobCats/BlobCat_Blep.png",
  "blepclose": "assets/blobcats/PNGs/BlobCats/BlobCat_BlepClose.png",
  "blepwink": "assets/blobcats/PNGs/BlobCats/BlobCat_BlepWink.png",
  "blush": "assets/blobcats/PNGs/BlobCats/BlobCat_Blush.png",
  "blushplead": "assets/blobcats/PNGs/BlobCats/BlobCat_BlushPlead.png",
  "boop": "assets/blobcats/PNGs/BlobCats/BlobCat_Boop.png",
  "boopblush": "assets/blobcats/PNGs/BlobCats/BlobCat_BoopBlush.png",
  "boopglare": "assets/blobcats/PNGs/BlobCats/BlobCat_BoopGlare.png",
  "boophappy": "assets/blobcats/PNGs/BlobCats/BlobCat_BoopHappy.png",
  "bot": "assets/blobcats/PNGs/BlobCats/BlobCat_Bot.png",
  "box": "assets/blobcats/PNGs/BlobCats/BlobCat_box.png",
  "bug": "assets/blobcats/PNGs/BlobCats/BlobCat_Bug.png",
  "camera": "assets/blobcats/PNGs/BlobCats/BlobCat_Camera.png",
  "cat": "assets/blobcats/PNGs/BlobCats/BlobCat.png",
  "chefskiss": "assets/blobcats/PNGs/BlobCats/BlobCat_ChefsKiss.png",
  "clown": "assets/blobcats/PNGs/BlobCats/BlobCat_Clown.png",
  "coffee": "assets/blobcats/PNGs/BlobCats/BlobCat_Coffee.png",
  "controller": "assets/blobcats/PNGs/BlobCats/BlobCat_Controller.png",
  "cookienom": "assets/blobcats/PNGs/BlobCats/BlobCat_CookieNom.png",
  "coolio": "assets/blobcats/PNGs/BlobCats/BlobCat_Coolio.png",
  "cowmeow": "assets/blobcats/PNGs/BlobCats/BlobCat_Cowmeow.png",
  "coy": "assets/blobcats/PNGs/BlobCats/BlobCat_Coy.png",
  "cozy": "assets/blobcats/PNGs/BlobCats/BlobCat_Cozy.png",
  "crown": "assets/blobcats/PNGs/BlobCats/BlobCat_Crown.png",
  "cry": "assets/blobcats/PNGs/BlobCats/BlobCat_Cry.png",
  "dab": "assets/blobcats/PNGs/BlobCats/BlobCat_Dab.png",
  "dead": "assets/blobcats/PNGs/BlobCats/BlobCat_Dead.png",
  "derpy": "assets/blobcats/PNGs/BlobCats/BlobCat_Derpy.png",
  "detective": "assets/blobcats/PNGs/BlobCats/BlobCat_Detective.png",
  "disguise": "assets/blobcats/PNGs/BlobCats/BlobCat_Disguise.png",
  "dizzy": "assets/blobcats/PNGs/BlobCats/BlobCat_Dizzy.png",
  "drool": "assets/blobcats/PNGs/BlobCats/BlobCat_Drool.png",
  "enjoy": "assets/blobcats/PNGs/BlobCats/BlobCat_Enjoy.png",
  "erm": "assets/blobcats/PNGs/BlobCats/BlobCat_Erm.png",
  "evil": "assets/blobcats/PNGs/BlobCats/BlobCat_Evil.png",
  "evildevil": "assets/blobcats/PNGs/BlobCats/BlobCat_EvilDevil.png",
  "evilknife": "assets/blobcats/PNGs/BlobCats/BlobCat_EvilKnife.png",
  "evilsneakydevil": "assets/blobcats/PNGs/BlobCats/BlobCat_EvilSneakyDevil.png",
  "exhausted": "assets/blobcats/PNGs/BlobCats/BlobCat_Exhausted.png",
  "expresionless": "assets/blobcats/PNGs/BlobCats/BlobCat_Expresionless.png",
  "extremejoy": "assets/blobcats/PNGs/BlobCats/BlobCat_ExtremeJoy.png",
  "eyeroll": "assets/blobcats/PNGs/BlobCats/BlobCat_Eyeroll.png",
  "eyes": "assets/blobcats/PNGs/BlobCats/BlobCat_Eyes.png",
  "facepalm": "assets/blobcats/PNGs/BlobCats/BlobCat_Facepalm.png",
  "fearful": "assets/blobcats/PNGs/BlobCats/BlobCat_Fearful.png",
  "fingerguns": "assets/blobcats/PNGs/BlobCats/BlobCat_FingerGuns.png",
  "fistbumpl": "assets/blobcats/PNGs/BlobCats/BlobCat_FistBumpL.png",
  "fistbumpr": "assets/blobcats/PNGs/BlobCats/BlobCat_FistBumpR.png",
  "flirty": "assets/blobcats/PNGs/BlobCats/BlobCat_Flirty.png",
  "flower": "assets/blobcats/PNGs/BlobCats/BlobCat_Flower.png",
  "frown": "assets/blobcats/PNGs/BlobCats/BlobCat_Frown.png",
  "ghostice": "assets/blobcats/PNGs/BlobCats/BlobCat_GhostIce.png",
  "ghosttilt": "assets/blobcats/PNGs/BlobCats/BlobCat_GhostTilt.png",
  "ghostwave": "assets/blobcats/PNGs/BlobCats/BlobCat_GhostWave.png",
  "gift": "assets/blobcats/PNGs/BlobCats/BlobCat_Gift.png",
  "giggle": "assets/blobcats/PNGs/BlobCats/BlobCat_Giggle.png",
  "glare": "assets/blobcats/PNGs/BlobCats/BlobCat_Glare.png",
  "grin": "assets/blobcats/PNGs/BlobCats/BlobCat_Grin.png",
  "happie": "assets/blobcats/PNGs/BlobCats/BlobCat_Happie.png",
  "heart": "assets/blobcats/PNGs/BlobCats/BlobCat_Heart.png",
  "heartbroken": "assets/blobcats/PNGs/BlobCats/BlobCat_HeartBroken.png",
  "hearteyes": "assets/blobcats/PNGs/BlobCats/BlobCat_HeartEyes.png",
  "hearthug": "assets/blobcats/PNGs/BlobCats/BlobCat_HeartHug.png",
  "heartshow": "assets/blobcats/PNGs/BlobCats/BlobCat_HeartShow.png",
  "hmph": "assets/blobcats/PNGs/BlobCats/BlobCat_Hmph.png",
  "hug": "assets/blobcats/PNGs/BlobCats/BlobCat_Hug.png",
  "huggies": "assets/blobcats/PNGs/BlobCats/BlobCat_Huggies.png",
  "hungry": "assets/blobcats/PNGs/BlobCats/BlobCat_Hungry.png",
  "hyperthink": "assets/blobcats/PNGs/BlobCats/BlobCat_Hyperthink.png",
  "idea": "assets/blobcats/PNGs/BlobCats/BlobCat_Idea.png",
  "itisfine": "assets/blobcats/PNGs/BlobCats/BlobCat_ItIsFine.png",
  "justright": "assets/blobcats/PNGs/BlobCats/BlobCat_JustRight.png",
  "kindasus": "assets/blobcats/PNGs/BlobCats/BlobCat_KindaSus.png",
  "kirby": "assets/blobcats/PNGs/BlobCats/BlobCat_Kirby.png",
  "kissy": "assets/blobcats/PNGs/BlobCats/BlobCat_Kissy.png",
  "knife": "assets/blobcats/PNGs/BlobCats/BlobCat_Knife.png",
  "laughing": "assets/blobcats/PNGs/BlobCats/BlobCat_Laughing.png",
  "lol": "assets/blobcats/PNGs/BlobCats/BlobCat_Lol.png",
  "lookie": "assets/blobcats/PNGs/BlobCats/BlobCat_Lookie.png",
  "love": "assets/blobcats/PNGs/BlobCats/BlobCat_Love.png",
  "magical": "assets/blobcats/PNGs/BlobCats/BlobCat_Magical.png",
  "masked": "assets/blobcats/PNGs/BlobCats/BlobCat_Masked.png",
  "melt": "assets/blobcats/PNGs/BlobCats/BlobCat_Melt.png",
  "meltedcompletely": "assets/blobcats/PNGs/BlobCats/BlobCat_MeltedCompletely.png",
  "meltheart": "assets/blobcats/PNGs/BlobCats/BlobCat_MeltHeart.png",
  "meltier": "assets/blobcats/PNGs/BlobCats/BlobCat_Meltier.png",
  "melttears": "assets/blobcats/PNGs/BlobCats/BlobCat_MeltTears.png",
  "meltthumbsup": "assets/blobcats/PNGs/BlobCats/BlobCat_MeltThumbsUp.png",
  "meltthumbsuptears": "assets/blobcats/PNGs/BlobCats/BlobCat_MeltThumbsUpTears.png",
  "middlefinger": "assets/blobcats/PNGs/BlobCats/BlobCat_MiddleFinger.png",
  "missing": "assets/blobcats/PNGs/BlobCats/BlobCat_Missing.png",
  "moremeltiie": "assets/blobcats/PNGs/BlobCats/BlobCat_MoreMeltiie.png",
  "nauseated": "assets/blobcats/PNGs/BlobCats/BlobCat_Nauseated.png",
  "nerd": "assets/blobcats/PNGs/BlobCats/BlobCat_Nerd.png",
  "nervous": "assets/blobcats/PNGs/BlobCats/BlobCat_Nervous.png",
  "nervoussweating": "assets/blobcats/PNGs/BlobCats/BlobCat_NervousSweating.png",
  "ninja": "assets/blobcats/PNGs/BlobCats/BlobCat_Ninja.png",
  "nom": "assets/blobcats/PNGs/BlobCats/BlobCat_Nom.png",
  "nomouth": "assets/blobcats/PNGs/BlobCats/BlobCat_NoMouth.png",
  "notif": "assets/blobcats/PNGs/BlobCats/BlobCat_Notif.png",
  "notlikethis": "assets/blobcats/PNGs/BlobCats/BlobCat_NotLikeThis.png",
  "notlikethiscry": "assets/blobcats/PNGs/BlobCats/BlobCat_NotLikeThisCry.png",
  "notlikethishyper": "assets/blobcats/PNGs/BlobCats/BlobCat_NotLikeThisHyper.png",
  "ohno": "assets/blobcats/PNGs/BlobCats/BlobCat_OhNO.png",
  "okihand": "assets/blobcats/PNGs/BlobCats/BlobCat_OkiHand.png",
  "openmouth": "assets/blobcats/PNGs/BlobCats/BlobCat_OpenMouth.png",
  "pain": "assets/blobcats/PNGs/BlobCats/BlobCat_Pain.png",
  "party": "assets/blobcats/PNGs/BlobCats/BlobCat_Party.png",
  "patangry": "assets/blobcats/PNGs/BlobCats/BlobCat_PatAngry.png",
  "pathiss": "assets/blobcats/PNGs/BlobCats/BlobCat_PatHiss.png",
  "pats": "assets/blobcats/PNGs/BlobCats/BlobCat_Pats.png",
  "patssad": "assets/blobcats/PNGs/BlobCats/BlobCat_PatsSad.png",
  "paw": "assets/blobcats/PNGs/BlobCats/BlobCat_Paw.png",
  "peek": "assets/blobcats/PNGs/BlobCats/BlobCat_Peek.png",
  "peekwithknife": "assets/blobcats/PNGs/BlobCats/BlobCat_PeekWithKnife.png",
  "pensive": "assets/blobcats/PNGs/BlobCats/BlobCat_Pensive.png",
  "pensive2": "assets/blobcats/PNGs/BlobCats/BlobCat_Pensive2.png",
  "photobomb": "assets/blobcats/PNGs/BlobCats/BlobCat_Photobomb.png",
  "pin": "assets/blobcats/PNGs/BlobCats/BlobCat_Pin.png",
  "pirate": "assets/blobcats/PNGs/BlobCats/BlobCat_Pirate.png",
  "pleadstare": "assets/blobcats/PNGs/BlobCats/BlobCat_PleadStare.png",
  "popcorn": "assets/blobcats/PNGs/BlobCats/BlobCat_Popcorn.png",
  "pout": "assets/blobcats/PNGs/BlobCats/BlobCat_Pout.png",
  "pouter": "assets/blobcats/PNGs/BlobCats/BlobCat_Pouter.png",
  "pray": "assets/blobcats/PNGs/BlobCats/BlobCat_Pray.png",
  "prayeyeroll": "assets/blobcats/PNGs/BlobCats/BlobCat_PrayEyeroll.png",
  "pumpkin": "assets/blobcats/PNGs/BlobCats/BlobCat_Pumpkin.png",
  "reach": "assets/blobcats/PNGs/BlobCats/BlobCat_Reach.png",
  "reachsad": "assets/blobcats/PNGs/BlobCats/BlobCat_ReachSad.png",
  "reachsobbing": "assets/blobcats/PNGs/BlobCats/BlobCat_ReachSobbing.png",
  "sad": "assets/blobcats/PNGs/BlobCats/BlobCat_Sad.png",
  "sadsob": "assets/blobcats/PNGs/BlobCats/BlobCat_SadSob.png",
  "salute": "assets/blobcats/PNGs/BlobCats/BlobCat_Salute.png",
  "scarecry": "assets/blobcats/PNGs/BlobCats/BlobCat_ScareCry.png",
  "scream": "assets/blobcats/PNGs/BlobCats/BlobCat_Scream.png",
  "shush": "assets/blobcats/PNGs/BlobCats/BlobCat_Shush.png",
  "signs": "assets/blobcats/PNGs/BlobCats/BlobCat_Signs.png",
  "sip": "assets/blobcats/PNGs/BlobCats/BlobCat_Sip.png",
  "sipglare": "assets/blobcats/PNGs/BlobCats/BlobCat_SipGlare.png",
  "sipsmile": "assets/blobcats/PNGs/BlobCats/BlobCat_SipSmile.png",
  "sleep": "assets/blobcats/PNGs/BlobCats/BlobCat_Sleep.png",
  "sleepless": "assets/blobcats/PNGs/BlobCats/BlobCat_Sleepless.png",
  "slightsmile": "assets/blobcats/PNGs/BlobCats/BlobCat_SlightSmile.png",
  "smiley": "assets/blobcats/PNGs/BlobCats/BlobCat_Smiley.png",
  "smileyclose": "assets/blobcats/PNGs/BlobCats/BlobCat_SmileyClose.png",
  "smilign": "assets/blobcats/PNGs/BlobCats/BlobCat_Smilign.png",
  "smilignmaximum": "assets/blobcats/PNGs/BlobCats/BlobCat_SmilignMaximum.png",
  "smilignmore": "assets/blobcats/PNGs/BlobCats/BlobCat_SmilignMore.png",
  "smilignopenmouth": "assets/blobcats/PNGs/BlobCats/BlobCat_SmilignOpenMouth.png",
  "smilignopenmouthsweating": "assets/blobcats/PNGs/BlobCats/BlobCat_SmilignOpenMouthSweating.png",
  "smirk": "assets/blobcats/PNGs/BlobCats/BlobCat_Smirk.png",
  "snore": "assets/blobcats/PNGs/BlobCats/BlobCat_Snore.png",
  "snugglebug": "assets/blobcats/PNGs/BlobCats/BlobCat_Snugglebug.png",
  "sobby": "assets/blobcats/PNGs/BlobCats/BlobCat_Sobby.png",
  "sorry": "assets/blobcats/PNGs/BlobCats/BlobCat_Sorry.png",
  "space": "assets/blobcats/PNGs/BlobCats/BlobCat_Space.png",
  "spy": "assets/blobcats/PNGs/BlobCats/BlobCat_Spy.png",
  "squeel": "assets/blobcats/PNGs/BlobCats/BlobCat_Squeel.png",
  "stare": "assets/blobcats/PNGs/BlobCats/BlobCat_Stare.png",
  "starstruck": "assets/blobcats/PNGs/BlobCats/BlobCat_Starstruck.png",
  "stopsign": "assets/blobcats/PNGs/BlobCats/BlobCat_StopSign.png",
  "surprise": "assets/blobcats/PNGs/BlobCats/BlobCat_Surprise.png",
  "sweat": "assets/blobcats/PNGs/BlobCats/BlobCat_Sweat.png",
  "tears": "assets/blobcats/PNGs/BlobCats/BlobCat_Tears.png",
  "teeth": "assets/blobcats/PNGs/BlobCats/BlobCat_Teeth.png",
  "terrified": "assets/blobcats/PNGs/BlobCats/BlobCat_Terrified.png",
  "think": "assets/blobcats/PNGs/BlobCats/BlobCat_Think.png",
  "thinkcool": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkCool.png",
  "thinkglare": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkGlare.png",
  "thinklove": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkLove.png",
  "thinkportal": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkPortal.png",
  "thinksmart": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkSmart.png",
  "thinksmirk": "assets/blobcats/PNGs/BlobCats/BlobCat_ThinkSmirk.png",
  "thumbsdown": "assets/blobcats/PNGs/BlobCats/BlobCat_ThumbsDown.png",
  "thumbsup": "assets/blobcats/PNGs/BlobCats/BlobCat_ThumbsUp.png",
  "tilt": "assets/blobcats/PNGs/BlobCats/BlobCat_Tilt.png",
  "trashed": "assets/blobcats/PNGs/BlobCats/BlobCat_Trashed.png",
  "triumph": "assets/blobcats/PNGs/BlobCats/BlobCat_Triumph.png",
  "unamused": "assets/blobcats/PNGs/BlobCats/BlobCat_Unamused.png",
  "upset": "assets/blobcats/PNGs/BlobCats/BlobCat_Upset.png",
  "upsidedown": "assets/blobcats/PNGs/BlobCats/BlobCat_UpsideDown.png",
  "uwu": "assets/blobcats/PNGs/BlobCats/BlobCat_uwu.png",
  "uwucry": "assets/blobcats/PNGs/BlobCats/BlobCat_uwuCry.png",
  "vibing": "assets/blobcats/PNGs/BlobCats/BlobCat_Vibing.png",
  "waitwhat": "assets/blobcats/PNGs/BlobCats/BlobCat_WaitWhat.png",
  "wave": "assets/blobcats/PNGs/BlobCats/BlobCat_Wave.png",
  "whaa": "assets/blobcats/PNGs/BlobCats/BlobCat_Whaa.png",
  "whistle": "assets/blobcats/PNGs/BlobCats/BlobCat_Whistle.png",
  "whistlelookaway": "assets/blobcats/PNGs/BlobCats/BlobCat_WhistleLookAway.png",
  "whuh": "assets/blobcats/PNGs/BlobCats/BlobCat_Whuh.png",
  "wink": "assets/blobcats/PNGs/BlobCats/BlobCat_Wink.png",
  "yaranaika": "assets/blobcats/PNGs/BlobCats/BlobCat_Yaranaika.png",
  "yilkes": "assets/blobcats/PNGs/BlobCats/BlobCat_Yilkes.png",
  "yipee": "assets/blobcats/PNGs/BlobCats/BlobCat_Yipee.png",
  "zippermouth": "assets/blobcats/PNGs/BlobCats/BlobCat_ZipperMouth.png",
)

// Sorted keys, used for suggestions when a name is not found.
#let blobcat-names = (
  "acab",
  "alien",
  "amused",
  "angel",
  "angery",
  "angryhammer",
  "arrow",
  "astonished",
  "aww",
  "ayo",
  "bandage",
  "bigsob",
  "blankie",
  "blankiescared",
  "blep",
  "blepclose",
  "blepwink",
  "blush",
  "blushplead",
  "boop",
  "boopblush",
  "boopglare",
  "boophappy",
  "bot",
  "box",
  "bug",
  "camera",
  "cat",
  "chefskiss",
  "clown",
  "coffee",
  "controller",
  "cookienom",
  "coolio",
  "cowmeow",
  "coy",
  "cozy",
  "crown",
  "cry",
  "dab",
  "dead",
  "derpy",
  "detective",
  "disguise",
  "dizzy",
  "drool",
  "enjoy",
  "erm",
  "evil",
  "evildevil",
  "evilknife",
  "evilsneakydevil",
  "exhausted",
  "expresionless",
  "extremejoy",
  "eyeroll",
  "eyes",
  "facepalm",
  "fearful",
  "fingerguns",
  "fistbumpl",
  "fistbumpr",
  "flirty",
  "flower",
  "frown",
  "ghostice",
  "ghosttilt",
  "ghostwave",
  "gift",
  "giggle",
  "glare",
  "grin",
  "happie",
  "heart",
  "heartbroken",
  "hearteyes",
  "hearthug",
  "heartshow",
  "hmph",
  "hug",
  "huggies",
  "hungry",
  "hyperthink",
  "idea",
  "itisfine",
  "justright",
  "kindasus",
  "kirby",
  "kissy",
  "knife",
  "laughing",
  "lol",
  "lookie",
  "love",
  "magical",
  "masked",
  "melt",
  "meltedcompletely",
  "meltheart",
  "meltier",
  "melttears",
  "meltthumbsup",
  "meltthumbsuptears",
  "middlefinger",
  "missing",
  "moremeltiie",
  "nauseated",
  "nerd",
  "nervous",
  "nervoussweating",
  "ninja",
  "nom",
  "nomouth",
  "notif",
  "notlikethis",
  "notlikethiscry",
  "notlikethishyper",
  "ohno",
  "okihand",
  "openmouth",
  "pain",
  "party",
  "patangry",
  "pathiss",
  "pats",
  "patssad",
  "paw",
  "peek",
  "peekwithknife",
  "pensive",
  "pensive2",
  "photobomb",
  "pin",
  "pirate",
  "pleadstare",
  "popcorn",
  "pout",
  "pouter",
  "pray",
  "prayeyeroll",
  "pumpkin",
  "reach",
  "reachsad",
  "reachsobbing",
  "sad",
  "sadsob",
  "salute",
  "scarecry",
  "scream",
  "shush",
  "signs",
  "sip",
  "sipglare",
  "sipsmile",
  "sleep",
  "sleepless",
  "slightsmile",
  "smiley",
  "smileyclose",
  "smilign",
  "smilignmaximum",
  "smilignmore",
  "smilignopenmouth",
  "smilignopenmouthsweating",
  "smirk",
  "snore",
  "snugglebug",
  "sobby",
  "sorry",
  "space",
  "spy",
  "squeel",
  "stare",
  "starstruck",
  "stopsign",
  "surprise",
  "sweat",
  "tears",
  "teeth",
  "terrified",
  "think",
  "thinkcool",
  "thinkglare",
  "thinklove",
  "thinkportal",
  "thinksmart",
  "thinksmirk",
  "thumbsdown",
  "thumbsup",
  "tilt",
  "trashed",
  "triumph",
  "unamused",
  "upset",
  "upsidedown",
  "uwu",
  "uwucry",
  "vibing",
  "waitwhat",
  "wave",
  "whaa",
  "whistle",
  "whistlelookaway",
  "whuh",
  "wink",
  "yaranaika",
  "yilkes",
  "yipee",
  "zippermouth",
)
